mkdir build
# cd build
    # "-DCMAKE_OSX_ARCHITECTURES=armv7;armv7s;arm64;i386;x86_64" \
cmake -S. -Bbuild -GXcode -DCMAKE_SYSTEM_NAME=iOS \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM=Q74A2VY23K \
    -DOPENCV_3P_LIB_INSTALL_PATH=lib/3rdparty \
    "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=10.0 \
    -DCMAKE_INSTALL_PREFIX=`pwd`/_install \
    -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO \
    -DAPPLE_FRAMEWORK=ON \
    -DCMAKE_IOS_INSTALL_COMBINED=YES
cmake --build build --config Release --target install --verbose